# T/F values defined in this file will need to be converted as Booleans with as.logical()
default:
    main_dir: 'C://MTC_tmpy//TM2_Run10//calibration_3332//reports//040923_BLvsRun10' # output folder of reports; also where gen_file populates templates
    TM2_data_dir: 'C://MTC_tmpy//TM2_Run10//calibration_3332'
    preprocess_suffix: '' # useful in case one wants to save out results of different run versions under the same project run folder
        
    gen_file:
        inputD: 'C://MTC_tmpy//RSummaries_templates'

    survey_comp:
        output_iteration: 1 # determines which CT-RAMP output files to pick up
        preprocess_r: T # preprocess the right hand side, TM2
        skip_l: F
        scenario: 'CHTSvsLink21'
        # left side: survey parameters
        left:
            name_model: 'CHTS'
            output_dir: 'C://MTC_tmpy//TM2//CHTS//'
            skim_dir: 'C://MTC_tmpy//TM2//CHTS//Skims//'
        # right side: TM2 parameters
        right:
            model_version: 'TM2'
            name_model: 'Link21'
    
    TM2_comp: # compare to other run, i.e. baseline
        preprocess_l: T # preprocess the left hand side, TM2 baseline
        preprocess_r: T # preprocess the right hand side, TM2
        skip_l: F
        scenario: 'TM2_baseline_vs_Run10'
        # left side: TM2 baseline parameters
        left:
            model_data_dir: 'C://MTC_tmpy//TM2_Base//calibration_3332'
            output_iteration: 3
            name_model: '030223_feedback_TM2'
            model_version: 'TM2'
        # right side: TM2 parameters
        right:
            name_model: 'Run10_IncreaseBARTtime'
            output_iteration: 4
            model_version: 'TM2'

    TM1.5_comp:
        output_iteration: 1 # determines which CT-RAMP output files to pick up
        #output_iteration_l
        #output_iteration_r
        preprocess_l: T # preprocess the left hand side, TM1.5
        preprocess_r: T # preprocess the right hand side, TM2 (or TM1.5 if needed)
        skip_l: F
        scenario: 'TM1.5_test'
        # left side: TM1.5 parameters
        left:
            model_data_dir: 'C://MTC_tmpy//TM2//Link21_Reports//TM1.5_results'
            name_model: '2015_TM1.5'
            model_version: 'TM1.5'
        # right side: TM2 parameters
        right:
            name_model: 'Link21'
            model_version: 'TM2'

