# T/F values defined in this file will need to be converted as Booleans with as.logical()
default:
    gen_file:
        inputD: 'C://Users//xchang//Downloads//templates'
        outputRootD: 'C://MTC_tmpy//TM2//Link21_Reports'

    survey_comp:
        output_iteration: 1 # determines which CT-RAMP output files to pick up
        main_dir: 'C://MTC_tmpy//TM2//Link21_Reports'
        preprocess_r: F # preprocess the right hand side, TM2
        model_data_dir: 'C://MTC_tmpy//TM2//2015_BaseY_P3Y2015//'
        skip_l: F # If you are doing model validation against survey data, please set skip_l = TRUE, otherwise, set it to FALSE.
        scenario: 'CHTSvsLink21_09-15-2022'
        # left side: survey parameters
        left:
            name_model: 'CHTS'
            output_dir: 'C://MTC_tmpy//TM2//Survey Data//'
            skim_dir: 'C://MTC_tmpy//TM2//Survey Data//Skims//'
        # right side: TM2 parameters
        right:
            model_version: 'TM2'
            name_model: 'Link21'
    
    TM1.5_comp:
        output_iteration: 1 # determines which CT-RAMP output files to pick up
        main_dir: 'C://MTC_tmpy//TM2//Link21_Reports'
        preprocess_l: F # preprocess the left hand side, TM1.5
        preprocess_r: F # preprocess the right hand side, TM2
        skip_l: F # If you are doing model validation against survey data, please set skip_l = TRUE, otherwise, set it to FALSE.
        scenario: 'TM1.5vsLink21_09-15-2022'
        # left side: TM1.5 parameters
        left:
            model_data_dir: 'C://MTC_tmpy//TM2//Link21_Reports//TM1.5_results'
            name_model: '2015_TM1.5'
            model_version: 'TM1.5'
        # right side: TM2 parameters
        right:
            model_data_dir: 'C://MTC_tmpy//TM2//2015_BaseY_P3Y2015//'
            name_model: 'Link21_09-07-2022'
            model_version: 'TM2'
            
            